name: Merge changes from main to feat/thought-leadership

on:
  push:
    branches:
      - main

jobs:
  merge-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Merge changes from main to feat/thought-leadership
        run: |
          git checkout feat/thought-leadership
          git merge main --no-ff --no-edit
          git push origin feat/thought-leadership
