name: Update Runbook Info
on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        working-directory: ./.github/runbook
        run: npm install
      - name: Run script
        run: |
          node .github/runbook/generate-runbook.mjs
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'runbook/*.json'
          commit_message: "Update Runbook info"